mycloud:
  port:
    eureka: 8761
  hostname:
    eureka: 127.0.0.1

server:
  port: 8031

spring:
  application:
    name: springcloud-hystrix-turbine

security:
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka
    role: -USER

eureka:
  instance:
  #给本地的 ip 去别名   后面就可以通过  XXXX:port 进行注册或是访问 需要修改(windows->system32-drivers->etc )文件盘的 hosts 文件属性  eg:直接在文件末尾加入   127.0.0.1   xxxx
    hostname: localhost
  #注册到此eureka 需要秘钥的两种方式中的   方式1
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    registerWithEureka: false # 禁止向服务注册自己
    fetchRegistry: false #
    serviceUrl:

#注册到此eureka 需要秘钥的两种方式 a
#  方式 1
#      defaultZone: http://${mycloud.hostname.eureka}:${mycloud.port.eureka}/eureka/
#  方式 2
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  dashboard:  #是否显示首页  默认为true
    enabled: true
    path: / #默认为 访问时为 / 即：访问地址   localhost:port/   假如配置的话： localhost:port/xxxx

turbine:
  aggregator:
    clusterConfig: SPRINGCLOUD-CONSUMER-FEIGN-WITH-HYSTRIX-FACTORY #要监控的 hystrix  service-id  需要大写，可监控多个 ，隔开
  app-config:  springcloud-consumer-feign-with-hystrix-factory #要监控的 hystrix  service-id  多个 ， 分割

