server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: springcloud-file-upload
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M  单个文件的大小
      max-request-size: 2500Mb   # Max request size，默认10M  上传的文件 总共大小
