mycloud:
  port:
    eureka: 8761
  hostname:
    eureka: 127.0.0.1

spring:
  application:
    name: springcloud-gateway-zuul-regx #指定注册的服务名  建议小写

server:
  port: 8041

security:
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka
    role: -USER

eureka:
  instance:
    prefer-ip-address: true #当鼠标放置 注册列表  左下角展示ip  地址就可以将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    instance-id: ${spring.application.name}:${server.port} #注册到服务上的 status 状态列表 名字   默认格式： 主机名：应用名称：端口 ${spring.application.name}:${spring.application.instance-id}${server.port}
    appname: ${spring.application.name} #默认使用的是 ${spring.application.name} 如果配置的话 注册首页 Application 下将会以appname 信息展示
  client:
#    health-check:
#      enable: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${mycloud.hostname.eureka}:${mycloud.port.eureka}/eureka/
