mycloud:
  port:
    eureka: 8761
  hostname:
    eureka: 127.0.0.1

spring:
  application:
    name: springcloud-gateway-zuul-fallback #指定注册的服务名  建议小写

server:
  port: 8045

security:
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka
    role: -USER

eureka:
  instance:
    prefer-ip-address: true #当鼠标放置 注册列表  左下角展示ip  地址就可以将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    instance-id: ${spring.application.name}:${server.port} #注册到服务上的 status 状态列表 名字   默认格式： 主机名：应用名称：端口 ${spring.application.name}:${spring.application.instance-id}${server.port}
    appname: ${spring.application.name} #默认使用的是 ${spring.application.name} 如果配置的话 注册首页 Application 下将会以appname 信息展示
  client:
#    health-check:
#      enable: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${mycloud.hostname.eureka}:${mycloud.port.eureka}/eureka/
zuul:
#  servlet-path: /         # 默认是/zuul , 上传文件需要加/zuul前缀才不会出现乱码，这个改成/ 即可不加前缀  当上传的是大文件类型时， 可通过 /zuul/** 绕过 http 请求的文件大小限制 eg; localhost:8040/zuul/service_id/upload
  routes:
    springcloud-provider:  # abc 可以顺便定义 但要唯一
      path: /users/**
    springcloud-file-upload:
      path: /file/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000  # 熔断超时 ribbon和hystrix是同时生效的，哪个值小哪个生效
ribbon:
  ConnectTimeout: 3000  # [ribbon超时时间]大于[熔断超时],那么会先走熔断，相当于你配的ribbon超时就不生效了  ribbon和hystrix是同时生效的，哪个值小哪个生效
  ReadTimeout: 60000
